Add primaries option to `bind_config` resource
sous-chefs/bind pull request #70
Opened 2021-11-23 04:21 UTC by detjensrobert

# Description

This was a missing option from the config file.

https://bind9.readthedocs.io/en/v9_16_23/reference.html?highlight=primaries#primaries-statement-definition-and-usage

## Issues Resolved

(none)

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

2021-11-23 15:28 UTC, damacus commented on resources/config.rb
> +property :primaries, [Hash],
```suggestion
property :primaries, Hash,
```

2021-11-23 15:29 UTC, damacus submitted a review, later dismissed
Just an odd array of a single value to fix and this is good to go 👍🏼

2021-11-24 00:38 UTC, ramereth requested changes

2021-11-24 00:38 UTC, ramereth commented on CHANGELOG.md
> +  - see
This looks incomplete.

2021-11-29 19:46 UTC, ramereth approved these changes

2021-11-29 19:47 UTC, merged

2021-11-29 19:47 UTC, kitchen-porter commented
Released as: [3.3.0](https://github.com/sous-chefs/bind/releases/tag/3.3.0)